plugins: 
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec_rails

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - "bin/*"
    - "config/deploy.rb"
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "spec/support/**/*"
    - "tmp/**/*"

Naming/PredicateMethod:
  Exclude:
    - app/lib/indexing/solr_cloud_helper.rb

Metrics/BlockLength:
  Exclude:
    - spec/lib/metadata_mapping_spec.rb
    - app/controllers/catalog_controller.rb

RSpec/AnyInstance:
  Exclude:
    - spec/lib/research_data_harvester_spec.rb
    - spec/system/show_pdc_describe_record_spec.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
