load_defaults: 7.19.2
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://#{ENV['lando_pdc_development_solr_conn_host']}:#{ENV['lando_pdc_development_solr_conn_port']}/solr/pdc-core-dev" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] ||  "http://#{ENV['lando_pdc_test_solr_conn_host']}:#{ENV['lando_pdc_test_solr_conn_port']}/solr/pdc-core-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
  solr_config_set: pdc-discovery-production
staging:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
  solr_config_set: pdc-discovery-staging
