load_defaults: 7.19.2
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://#{ENV['lando_pdc_development_solr_conn_host']}:#{ENV['lando_pdc_development_solr_conn_port']}/solr/pdc-core-dev" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] ||  "http://#{ENV['lando_pdc_test_solr_conn_host']}:#{ENV['lando_pdc_test_solr_conn_port']}/solr/pdc-core-test" %>
  solr_config_set: pdc-discovery-test
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
  solr_config_set: pdc-discovery-production
staging:
  adapter: solr
  # Temporarily go straight to a Solr node (lib-solr-staging4)
  # instead of going through the load balancer (lib-solr8-staging configured via Ansible).
  # I am not sure this will by pass Zookeper but worth a shot.
  url: http://lib-solr-staging4.princeton.edu:8983/solr/pdc-discovery-staging
  solr_config_set: pdc-discovery-staging
