load_defaults: 7.19.2
development:
  adapter: solr
  url: <%= "http://localhost:9000/solr/pdc-discovery-staging-hector" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] ||  "http://#{ENV['lando_pdc_test_solr_conn_host']}:#{ENV['lando_pdc_test_solr_conn_port']}/solr/pdc-core-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
staging:
  adapter: solr
  url: <%= ENV['SOLR_URL'] %>
