default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 40)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000
  host: <%= ENV["lando_pdc_database_conn_host"] || ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["lando_pdc_database_conn_port"] || 5432 %>
  username: <%= ENV["lando_pdc_database_creds_user"] || ENV["DB_USERNAME"] %>
  password: <%= ENV["lando_pdc_database_creds_password"] || ENV["DB_PASSWORD"] %>
  database: <%= ENV['DATABASE'] %>

development:
  <<: *default
  database: pdc_development

test:
  <<: *default
  database: pdc_test

production:
  <<: *default

staging:
  <<: *default
