default: &default
  dataspace_url: <%= ENV["DATASPACE_URL"] || "https://dataspace-dev.princeton.edu" %>
  pdc_describe_rss: <%= ENV["PDC_DESCRIBE_RSS"] || "https://pdc-describe-staging.princeton.edu/describe/works.rss" %>
  index_pdc_describe: true
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  dataspace_url: <%= ENV["DATASPACE_URL"] %>
  plausible_site_id: <%= "datacommons.princeton.edu/discovery" %>
  pdc_describe_rss: <%= ENV["PDC_DESCRIBE_RSS"] || "https://pdc-describe-prod.princeton.edu/describe/works.rss" %>
  index_pdc_describe: false

staging:
  <<: *default
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>
