default: &default
  dataspace_url: <%= ENV["DATASPACE_URL"] || "https://dataspace.princeton.edu" %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  dataspace_url: <%= ENV["DATASPACE_URL"] %>

staging:
  <<: *default
