default: &default
  dataspace_url: <%= ENV["DATASPACE_URL"] || "https://dataspace-dev.princeton.edu" %>
  pdc_describe_rss: <%= ENV["PDC_DESCRIBE_RSS"] || "https://pdc-describe-prod.princeton.edu/describe/works.rss" %>
  index_pdc_describe: true
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>
  globus_collection_uuid: <%= "7c83af0e-d88c-4f39-96b5-eeb302d04070" %>
  contact_email: "prds@princeton.edu"

development:
  <<: *default

test:
  <<: *default
  globus_collection_uuid: <%= "xxxx-yyyy-zzzz-aaaa-bbbb" %>

production:
  <<: *default
  dataspace_url: <%= ENV["DATASPACE_URL"] %>
  plausible_site_id: <%= "datacommons.princeton.edu/discovery" %>
  pdc_describe_rss: <%= ENV["PDC_DESCRIBE_RSS"] || "https://pdc-describe-prod.princeton.edu/describe/works.rss" %>
  index_pdc_describe: true
  # Notice that we use the Globus Collection UUID for the "guest" collection in
  # Globus which is public and read-only (as opposed to the "managed" collection)
  globus_collection_uuid: <%= "bb151d8e-ea3f-4612-b357-94d07f538f0c" %>

staging:
  <<: *default
  pdc_describe_rss: <%= ENV["PDC_DESCRIBE_RSS"] || "https://pdc-describe-staging.princeton.edu/describe/works.rss" %>
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>
