default: &default
  dataspace_url: <%= ENV["DATASPACE_URL"] || "https://dataspace-dev.princeton.edu" %>
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>

development:
  <<: *default

test:
  <<: *default

# TODO: switch plausible_site_id to production id once we create one in Plausible
production:
  <<: *default
  dataspace_url: <%= ENV["DATASPACE_URL"] %>
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>

staging:
  <<: *default
  plausible_site_id: <%= "pdc-discovery-staging.princeton.edu" %>
