---
name: Deploy API docs to GitHub Pages
on:
  push:
    branches: ['main']
    # paths:
    #   - '.github/workflows/pages.yml'
    #   - '.yardopts'
    #   - 'lib/**'
    #   - 'Gemfile'
    #   - '**.txt'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy_yard:
    # the deploy environment (not to be confused with env)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: Build and deploy YARD
    steps:
      - uses: kachick/deploy-yard-to-pages@v1.3.0
        id: deployment
        with:
          # default `doc` as default of `.yardopts`
          # output-dir: 'doc'
          # default version is 3.2
          ruby-version: '3.2'
